export default {
    1:  "ie",
    2:  "edge",
    3:  "firefox",
    4:  "chrome",
    5:  "safari",
    6:  "opera",
    7:  "ios_saf",
    8:  "op_mini",
    9:  "android",
    10: "bb",
    11: "op_mob",
    12: "and_chr",
    13: "and_ff",
    14: "ie_mob",
    15: "and_uc",
    16: "samsung",
};
